plugins:
  - jest

env:
  node: true
  jest: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: 
  no-console: 0
  import/extensions: 
  - error
  - ignorePackages
  - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]